### ISSUE TITLE
403 on posting status of the commit in Gitlab API v4

### ISSUE THREAD

**Issue by degree** [gabrie-allaigre/java-gitlab-api#3]
We are using Gitlab 10 with API v4 to report _preview_ and _issues_ analysis from maven build (also using your sonar gitlab plugin). First even successful build produces error in the build logs (look it up at the end). Configured user is allowed to comment on the commit (commit has appeared after the build). HOST/PROJECT_ID/COMMIT_ID just hide away our setup but they are resolved to proper values.

From my point of view the url `https://HOST/api/v4/projects/PROJECT_ID/statuses/COMMIT_ID` url is wrong. With newer API it should be `https://HOST/api/v4/projects/PROJECT_ID/repository/commits/COMMIT_ID/statuses` in GitLabAPICommits.postCommitStatus.

```[ERROR] Unable to update commit status
com.talanlabs.gitlab.api.v4.GitLabAPIException: {"message":"403 Forbidden"}
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.handleAPIError(GitLabHTTPRequestor.java:378) ~[java-gitlab-api-1.3.0.jar:na]
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.to(GitLabHTTPRequestor.java:125) ~[java-gitlab-api-1.3.0.jar:na]
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.to(GitLabHTTPRequestor.java:95) ~[java-gitlab-api-1.3.0.jar:na]
	at com.talanlabs.gitlab.api.v4.services.GitLabAPICommits.postCommitStatus(GitLabAPICommits.java:181) ~[java-gitlab-api-1.3.0.jar:na]
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV4Wrapper.createOrUpdateSonarQubeStatus(GitLabApiV4Wrapper.java:211) ~[sonar-gitlab-plugin-2.1.0.jar:na]
	at com.talanlabs.sonar.plugins.gitlab.CommitFacade.createOrUpdateSonarQubeStatus(CommitFacade.java:103) [sonar-gitlab-plugin-2.1.0.jar:na]
	at com.talanlabs.sonar.plugins.gitlab.CommitIssuePostJob.execute(CommitIssuePostJob.java:87) [sonar-gitlab-plugin-2.1.0.jar:na]
	at org.sonar.batch.postjob.PostJobWrapper.executeOn(PostJobWrapper.java:58) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:87) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119) [sonar-scanner-engine-shaded-5.6.6.jar:na]
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63) [sonar-scanner-api-batch3297449586383539607.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-api-2.9.0.887.jar:na]
	at com.sun.proxy.$Proxy57.execute(Unknown Source) [na:na]
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233) [sonar-scanner-api-2.9.0.887.jar:na]
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-api-2.9.0.887.jar:na]
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:77) [sonar-maven-plugin-3.3.0.603.jar:na]
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:139) [sonar-maven-plugin-3.3.0.603.jar:na]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) [maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863) [maven-embedder-3.3.9.jar:3.3.9]
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) [maven-embedder-3.3.9.jar:3.3.9]
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199) [maven-embedder-3.3.9.jar:3.3.9]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:na]
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://HOST/api/v4/projects/PROJECT_ID/statuses/COMMIT_ID
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_121]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_121]
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.parse(GitLabHTTPRequestor.java:336) ~[java-gitlab-api-1.3.0.jar:na]
	at com.talanlabs.gitlab.api.v4.http.GitLabHTTPRequestor.to(GitLabHTTPRequestor.java:123) ~[java-gitlab-api-1.3.0.jar:na]
	... 56 common frames omitted```

**Comment by gabrie-allaigre** [comment]
Hi,
What right does the user sonar have on the project?

**Comment by degree** [comment]
Reporter. If I execute the same with curl with my rights (as Owner) i just get 404. Anything meaningful will be returned only with url I have provided.

Worth saying that method that gets statuses has another url (same as I have provided) as method below that posts.

**Comment by degree** [comment]
Checkout [this line](https://github.com/gabrie-allaigre/java-gitlab-api/blob/5dbd1e8eeca68c5e18b626b5cb9199b8b3acce31/src/main/java/com/talanlabs/gitlab/api/v4/services/GitLabAPICommits.java#L158) in getCommitStatuses and [this](https://github.com/gabrie-allaigre/java-gitlab-api/blob/5dbd1e8eeca68c5e18b626b5cb9199b8b3acce31/src/main/java/com/talanlabs/gitlab/api/v4/services/GitLabAPICommits.java#L180) in postCommitStatus.

**Comment by gabrie-allaigre** [comment]
Reporter can't change commit status

**Comment by degree** [comment]
I have seen another error in the logs with 403 to proper URL. So I am raising rights to Developer.

**Comment by degree** [comment]
I am doing another test with Developer rigths: if resolved then I will close the issue.
Thank you.

**Comment by gabrie-allaigre** [comment]
thanks

**Comment by degree** [comment]
Yes, status of the pipeline is being updated. I have overlooked developer role. Merci beaucoup!

**Comment by Blarne** [comment]
I opened https://github.com/gabrie-allaigre/java-gitlab-api/issues/7 but this issue had same solution. But still not merged and no MR exists. When will be fixed? Or can I create MR?
